export default {
    CHANGE_IS_LOADING: 'CHANGE_IS_LOADING',
    CHANGE_SHOW_USER_FORM: 'CHANGE_SHOW_USER_FORM',
    CHANGE_IS_SIGN_UP: 'CHANGE_IS_SIGN_UP',
    CHANGE_ALERT_MESSAGE: 'CHANGE_ALERT_MESSAGE',
    CHANGE_CONFIRM_MESSAGE: 'CHANGE_CONFIRM_MESSAGE',
    SET_CONFIRM_HANDLER: 'SET_CONFIRM_HANDLER',
    SET_CANCEL_HANDLER: 'SET_CANCEL_HANDLER',
    SET_USER: 'SET_USER',
    SET_SHOPPING_CART: 'SET_SHOPPING_CART',
};