export default {
    CHANGE_IS_LOADING: 'CHANGE_IS_LOADING',
    CHANGE_SHOW_USER_FORM: 'CHANGE_SHOW_USER_FORM',
    CHANGE_IS_SIGN_UP: 'CHANGE_IS_SIGN_UP',
    CHANGE_ALERT_MESSAGE: 'CHANGE_ALERT_MESSAGE',
    SET_USER: 'SET_USER'
}